### ISSUE TITLE
Création de nouveaux fichiers

### ISSUE THREAD

**Issue by 4sStylZ** [GuimDev/LeeKloud#4]
Hello,

J’ai tenté de prendre des fichiers d’IA d’un de mes comptes pour les mettre dans le dossier de mon second compte en ésperant que ça rende accessibles les fichiers dans l’editeur leekwars. 

Hors cela n’a rien fait du tout et j’ai toujours les `update: ok` dans le fichier js.

J’imagine que la fonctionnalité n’éxiste tout simplement pas ?

Merci à toi.

**Comment by GuimDev** [comment]
Nop de lui même il ne crée aucun fichier.

**Comment by 4sStylZ** [comment]
Merci pour les réponses.

**Comment by GuimDev** [comment]
C'est voulu qu'il ne fasse "rien" de lui même pour éviter les soucis, normalement il y a la commande create. :/
